# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('maxHP', models.IntegerField()),
                ('maxAtk', models.IntegerField()),
                ('maxDef', models.IntegerField()),
                ('minHP', models.IntegerField()),
                ('minAtk', models.IntegerField()),
                ('minDef', models.IntegerField()),
                ('maxLevel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('modHP', models.FloatField()),
                ('modAtk', models.FloatField()),
                ('modDef', models.FloatField()),
                ('directAttack', models.IntegerField()),
                ('directAttackPer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('noAtk', models.PositiveIntegerField(default=0)),
                ('allyAtkPer', models.PositiveIntegerField(default=0)),
                ('selfAtkPer', models.PositiveIntegerField(default=0)),
                ('modAtk', models.IntegerField()),
                ('modDef', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Player', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petprototype',
            name='skills',
            field=models.ManyToManyField(to='Web.PetSkill'),
        ),
        migrations.AddField(
            model_name='pet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Profile'),
        ),
        migrations.AddField(
            model_name='pet',
            name='proto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.PetPrototype'),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.ManyToManyField(to='Web.PetStatus'),
        ),
    ]
